apiVersion: v1
kind: Service
metadata: 
    name: clusterIP
    labels: 
      app: clusterIP
spec:
    selector:
          app: nginx   
    ports: 
        - protocol: TCP
          port: 80 
    type: ClusterIP
  
