apiVersion: batch/v1
kind: Job
metadata: 
  name: demo-job
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: demo-job
    spec: 
      containers: 
        - name: batch-cont
          image: busybox:latest
          command: ["sh" , "-c" , "echo hello world! && sleep 10"] 
      restartPolicy: Never
