apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  volumes:  # Corrected: plural
    - name: vol
      persistentVolumeClaim:
        claimName: pvc 
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:  
      - name: vol
        mountPath: /usr/share/nginx/html
