apiVersion: v1
kind: persistentVolumeClaim
metadata: 
  name: pvc
  labels: 
    app: pvc
spec:    
  storageClassName: standard
  volumeMode: Filesystem
  accessMode: 
    - ReadWriteOnce
  resources: 
    request: 
      storage: 2Gi
