apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-exist
  labels: 
    app: rs-exist
spec: 
  selector:
    matchExpressions: 
      - {key: app , operator: NotIn , values: [rsapp,  new-app , nginx-in]  }
  replicas: 3 
  template: 
    metadata:
      name: nginx
      labels: 
        app: nginx
    spec: 
      containers:
        - name: nginx
          image: nginx:latest
          ports: 
            - containerPort: 80
